import { Project } from "@/app/_types/project";

export const projects: Project[] = [
  {
    title: "Dedicated Server Infrastructure for Multiplayer Game",
    slug: "dedicated-server-infrastructure",
    description:
      "Scalable AWS-backed server architecture with user authentication and real-time stat tracking.",
    longDescription:
      "Designed and deployed a scalable backend architecture for a multiplayer game using Amazon Web Services. Integrated EC2 and Anywhere Fleets to support both cloud-hosted and user-hosted servers, enabling flexible compute allocation. Implemented secure user authentication via AWS Cognito, allowing cross-platform logins and persistent player profiles. Leveraged DynamoDB for real-time stat tracking and leaderboard generation, with multiple Lambda functions orchestrating stat updates and retrieval. Built a modular gameplay interface to display career stats, match history, and leaderboard rankings dynamically.",
    features: [
      "EC2 and Anywhere Fleets for server hosting",
      "Cross-platform user authentication via Cognito",
      "Real-time stat tracking with DynamoDB",
      "Leaderboard generation and career stats",
      "Multiple Lambda functions for stat updates and retrieval",
    ],
    tech: [
      "AWS",
      "EC2",
      "Anywhere Fleets",
      "Cognito",
      "DynamoDB",
      "Lambda",
      "JavaScript",
    ],
    tags: [
      "AWS",
      "Server Hosting",
      "Multiplayer Backend",
      "User Authentication",
      "Leaderboard System",
      "Cloud Architecture",
    ],
    thumbnail: "/projects/dedicated-servers/Dedicated-Servers-Game.png",
    images: [
      "/projects/dedicated-servers/Dedicated-Servers-Career.png",
      "/projects/dedicated-servers/Dedicated-Servers-Leaderboard.png",
    ],
    category: "game",
    video: "tmofhnkKzoM",
    date: "2025",
  },
  {
    title: "Multiplayer Dungeon Crawler",
    slug: "horror-dungeon-crawler",
    description:
      "4-player horror dungeon crawler built with Unreal Engine’s Gameplay Ability System.",
    tags: ["Unreal Engine", "Multiplayer", "GAS", "AI", "Combat", "Networking"],
    longDescription:
      "Developed a 4-player horror dungeon crawler using Unreal Engine’s Gameplay Ability System (GAS). Built core gameplay around class-based mechanics, light-triggered debuffs, and scalable combat systems. Implemented advanced AI using behavior trees and C++/Blueprint hybrid logic. Designed multiplayer architecture with lobby selection, persistent SaveGame slots, and insurance-based inventory retention.",
    features: [
      "Gameplay Ability System for scalable combat and class mechanics",
      "Multiplayer lobby selection and session management",
      "Light-based debuff system tied to environment triggers",
      "Advanced AI using behavior trees and GAS-driven ability activation",
      "SaveGame system with multiple slots and persistent progression",
      "Insurance inventory system for death-safe item retention",
    ],
    tech: [
      "Unreal Engine 5",
      "Gameplay Ability System (GAS)",
      "C++",
      "Blueprints",
      "Behavior Trees",
      "Multiplayer Networking",
      "SaveGame System",
    ],
    thumbnail: "/projects/dungeon/Dungeon-Thumbnail.png",
    images: [
      "/projects/dungeon/Dungeon-Inventory.png",
      "/projects/dungeon/Dungeon-Mobs.png",
      "/projects/dungeon/Dungeon-Boss1.png",
      "/projects/dungeon/Dungeon-Boss2.png",
      "/projects/dungeon/Dungeon-Boss3.png",
      "/projects/dungeon/Dungeon-Boss5.png",
    ],
    category: "game",
    video: "GKxt2N9Is2Q",
    date: "2024",
  },
  {
    title: "Blaster Game",
    slug: "blaster-game",
    description:
      "Third-person online multiplayer shooter built in Unreal Engine with advanced networked gameplay systems.",
    tags: [
      "Unreal Engine",
      "Multiplayer",
      "Shooter",
      "C++",
      "Replication",
      "Server Rewind",
      "Gamemodes",
    ],
    longDescription:
      "Solo-developed third-person online multiplayer shooter built in Unreal Engine using C++. Features include projectile and hitscan weapons, server-side rewind, and server cheat detection. Implemented multiple gamemodes (Free-For-All, Team Deathmatch, Capture the Flag), randomized power-ups, and robust replication logic. Focused heavily on network programming, gameplay systems, and competitive mechanics.",
    features: [
      "Projectile and hitscan weapons including sniper, shotgun, rocket launcher, and rifle",
      "Server-side rewind for fair hit registration across varying client pings",
      "Server cheat detection to validate client-side variables like damage and fire rate",
      "Multiple gamemodes: Free-For-All, Team Deathmatch, Capture the Flag",
      "Randomized power-ups including shields, speed boosts, health, and jump enhancements",
      "Replicated gameplay systems with clean C++ and Blueprint hybrid logic",
    ],
    tech: [
      "Unreal Engine 5",
      "C++",
      "Blueprints",
      "Multiplayer Networking",
      "Replication",
      "Server Rewind",
      "Gamemode Framework",
    ],
    thumbnail: "/projects/blaster/Blaster-Main.png",
    images: [
      "/projects/blaster/Blaster-Alt.png",
      "/projects/blaster/Blaster-Lobby.png",
      "/projects/blaster/Blaster-Game.jpeg",
    ],
    category: "game",
    video: "nAwYcq2vvoI",
    date: "2023",
  },
  {
    title: "Nature Simulation",
    slug: "nature-simulation",
    description:
      "Survival sandbox prototype built for a university assignment, featuring AI-driven gameplay and environmental systems.",
    tags: [
      "Unreal Engine",
      "Simulation",
      "AI",
      "Survival",
      "Day/Night Cycle",
      "C++",
      "Player Attributes",
    ],
    longDescription:
      "Developed a nature-sandbox simulation game inspired by titles like Spore and Equilinox. Built for a university assignment focused on environmental gameplay and autonomous systems. Implemented AI for both player and enemies, with Sims-style autonomous actions and override mechanics. Designed a dynamic day/night cycle that affects world temperature and forces shelter-seeking behavior. Integrated survival attributes including health, hunger, and temperature, requiring players to manage resources and adapt to environmental threats.",
    features: [
      "Autonomous player AI with override mechanics inspired by The Sims",
      "Enemy AI behavior based on level comparison and dynamic aggression",
      "Day/night cycle that drives temperature changes and shelter-seeking gameplay",
      "Survival attributes including health, hunger, and temperature",
      "Combat and shelter mechanics tied to environmental conditions",
      "Assignment-driven design focused on nature-sandbox simulation principles",
    ],
    tech: [
      "Unreal Engine 5",
      "C++",
      "Blueprints",
      "AI Systems",
      "Day/Night Cycle",
      "Player Attribute Management",
    ],
    thumbnail: "/projects/simulation/Sim-Main.png",
    images: [
      "/projects/simulation/Sim-Bear.png",
      "/projects/simulation/Sim-Island.png",
    ],
    category: "game",
    video: "RayA4MKlG-c",
    date: "2023",
  },
  {
    title: "Dominium",
    slug: "dominium",
    description:
      "First-person city builder prototype developed in a university group project using Unreal Engine and AI-driven systems.",
    tags: [
      "Unreal Engine",
      "City Builder",
      "AI",
      "Simulation",
      "C++",
      "Day/Night Cycle",
      "Multiplayer",
    ],
    longDescription:
      "Dominium was built as part of a university group project where we simulated a real studio workflow using Jira and GitHub. I worked as a programmer on the team, focusing on core gameplay systems and AI behaviour. The game mixes first-person interaction with city-building mechanics, letting players place structures, expand their settlement, and work toward milestone goals. AI workers gather resources based on assigned jobs, follow daily routines, and return home at night instead of passively generating resources. A day/night cycle drives much of the city`s activity, influencing worker behaviour and pacing the player`s progression.",
    features: [
      "First-person gameplay with direct interaction and task resolution",
      "Building placement system for city expansion and milestone tracking",
      "AI workers with job assignment, resource gathering, and daily routines",
      "Day/night cycle affecting AI behavior and city dynamics",
      "Collaborative development using Jira and GitHub in a simulated studio workflow",
      "Stylized environment with low-poly assets and sunset lighting",
    ],
    tech: [
      "Unreal Engine 5",
      "C++",
      "Blueprints",
      "AI Systems",
      "Day/Night Cycle",
      "Multiplayer Architecture",
      "Version Control (GitHub)",
      "Project Management (Jira)",
    ],
    thumbnail: "/projects/dominium/Dominium-Main.jpg",
    images: [
      "/projects/dominium/Dominium-Demo.png",
      "/projects/dominium/Dominium-Well.png",
    ],
    category: "game",
    video: "FFHdV46PCWA",
    date: "2023",
  },
  {
    title: "Mortalis",
    slug: "mortalis",
    description:
      "MMORPG and Looter Arena project where I led development, architecture, and team workflow across a startup environment.",
    tags: [
      "Unreal Engine",
      "MMORPG",
      "Looter Arena",
      "C++",
      "Networking",
      "Leadership",
      "Architecture",
      "Team Management",
    ],
    longDescription:
      "I led development for an MMORPG and Looter Arena game, overseeing the overall architecture, code quality, and core gameplay systems. My role involved directing the team`s workflow through sprint planning, backlog refinement, milestone tracking, and weekly meetings. I maintained and reviewed all developer code while mentoring the team through technical guidance, pair programming, and structured code reviews. I worked closely with designers, artists, and producers to ensure gameplay features aligned with the company`s vision, and regularly presented progress to the wider team. My technical contributions included building a flexible inventory system, intelligent enemy AI, and advanced combat and ability mechanics in C++.",
    features: [
      "Led development across architecture, gameplay systems, and code quality",
      "Sprint planning, backlog refinement, milestone tracking, and weekly team meetings",
      "Mentored developers through code reviews, pair programming, and technical guidance",
      "Collaborated with designers, artists, and producers to align with the company vision",
      "Presented development progress to the wider team and stakeholders",
      "Developed adaptable inventory systems, intelligent enemy AI, and advanced combat/ability mechanics",
    ],
    tech: [
      "Unreal Engine 5",
      "C++",
      "Blueprints",
      "Multiplayer Networking",
      "Gameplay Architecture",
      "AI Systems",
      "Ability Systems",
      "Team Leadership",
    ],
    thumbnail: "/projects/mortalis/Mortalis-Main2.png",
    category: "startup",
    website: "https://mortalisgame.com/",
  },
  {
    title: "ENDs",
    slug: "ends",
    description:
      "Open-world systems project focused on large-scale AI, vehicle simulation, and quest framework development.",
    tags: [
      "Unreal Engine",
      "Mass AI",
      "C++",
      "AI Systems",
      "Vehicles",
      "Open World",
      "Quest Framework",
    ],
    longDescription:
      "ENDs is an open-world systems project where I worked on large-scale AI, vehicle simulation, and quest framework improvements. I integrated Unreal Engine’s Mass framework to support high-volume pedestrian and vehicle AI, and expanded the quest system using C++ to make it more flexible and scalable. I also implemented enemy chasing behaviour, realistic vehicle driving, and deformation systems. The focus of my work was on performance-friendly AI, systemic gameplay, and building foundations for a large, dynamic world.",
    features: [
      "Integrated Unreal Engine Mass framework for large-scale pedestrian and vehicle AI",
      "Expanded and improved the quest framework using C++",
      "Implemented enemy chasing AI and behaviour systems",
      "Developed realistic vehicle driving and deformation",
      "Worked with new Unreal Engine technologies for open-world scalability",
    ],
    tech: [
      "Unreal Engine 5",
      "Mass AI",
      "C++",
      "Blueprints",
      "Vehicle Simulation",
      "AI Behaviour Systems",
      "Quest Framework",
    ],
    thumbnail: "/projects/ends/ENDS-Main.png",
    category: "startup",
    website: "https://store.steampowered.com/app/2870130/ENDS/",
  },
  {
    title: "Darkflow",
    slug: "darkflow",
    description:
      "Sci-fi adventure RPG where I focused on core gameplay systems including ballistics, AI, and movement mechanics.",
    tags: [
      "Unreal Engine",
      "RPG",
      "Sci-Fi",
      "C++",
      "Gameplay Systems",
      "AI",
      "Movement Mechanics",
    ],
    longDescription:
      "Darkflow is a sci-fi adventure RPG set across a universe-spanning storyline. I worked as a developer in a small team, focusing on core gameplay mechanics and systemic features. My contributions included developing accurate ballistic behaviour for weapons, implementing intelligent AI for companion turrets, and creating fluid hoverboard movement. The project blends narrative-driven progression with combat against alien factions, cybernetically enhanced enemies, and larger forces shaping the world behind the scenes.",
    features: [
      "Accurate ballistic weapon behaviour",
      "Intelligent companion turret AI",
      "Fluid hoverboard movement mechanics",
      "Combat against alien factions and cyber-enhanced enemies",
      "Narrative-driven sci-fi adventure across multiple worlds",
    ],
    tech: [
      "Unreal Engine 5",
      "C++",
      "Blueprints",
      "AI Systems",
      "Movement Mechanics",
      "Gameplay Programming",
    ],
    thumbnail: "/projects/darkflow/Darkflow-Main.jpg",
    category: "startup",
    website: "https://store.steampowered.com/app/2457820/Darkflow/",
  },
  {
    title: "Converso SaaS",
    slug: "converso",
    description:
      "A SaaS for creating AI companions that help you with your studies!",
    tags: [
      "TypeScript",
      "Clerk",
      "Sentry",
      "Billing",
      "Subscriptions",
      "Authentication",
      "User Login",
      "Voice Input",
    ],
    longDescription:
      "Built a full-stack SaaS for users to create AI Companions that help them with their studies using Vapi. Users can log-in with Clerk and subscribe to different plans and take payments, create conversations with multiple different AI, bookmark conversations, create their own companions and view a detailed profile on their journey.",
    features: [
      "Create AI Companions",
      "Have life-like conversations with AI",
      "Bookmark Companions",
      "User login and profile page",
      "Responsive multi-page layout using NextJs",
      "Responsive design using modern components",
      "Search filter and Category filters",
      "SQL queries for filters, bookmarks, conversations and companions",
      "Sentry used for detailed errors from users.",
    ],
    tech: [
      "TypeScript",
      "React",
      "Lottie",
      "ShadCn",
      "SQL",
      "PostgreSQL",
      "Authentication",
      "Vapi",
      "Sentry",
    ],
    thumbnail: "/projects/converso/converso-main.png",
    images: [
      "/projects/converso/converso-main.png",
      "/projects/converso/converso-clibrary.png",
      "/projects/converso/converso-conversation.png",
      "/projects/converso/converso-profile.png",
      "/projects/converso/converso-plans.png",
      "/projects/converso/converso-cbuilder.png",
    ],
    category: "web",
    website: "https://converso-saas-two.vercel.app/",
    github: "https://github.com/Dylan-JM/saas-app",
  },
  {
    title: "Game Forum",
    slug: "game-forum",
    description:
      "Forum-style web app for posting reviews, bug reports, and suggestions about a video game.",
    tags: [
      "React",
      "Express",
      "SQL",
      "Full Stack",
      "Forum",
      "Routing",
      "User Login",
      "Database Polling",
    ],
    longDescription:
      "Built a full-stack forum website where users can post reviews, bug reports, suggestions, and general feedback about a video game. The app supports dynamic routing, category filtering, post deletion, and like functionality. I implemented user login and profiles as an extra feature beyond the assignment brief. The frontend is built with React and React Router, and the backend uses Express with SQL queries to fetch and manage post data. I designed the database schema and seeded it with realistic data, then used .map() and polling logic to render new posts in real time. The UI is responsive and intuitive, with multi-page navigation and a clean post creation flow. This was created in week 8 of my Tech Educators Software Development Bootcamp.",
    features: [
      "Create, read, and delete posts with category tagging",
      "Dynamic routing for individual posts and category views",
      "Like functionality to upvote posts",
      "User login and profile page",
      "Responsive multi-page layout using React Router",
      "Database polling with useEffect and interval logic",
      "Seeded realistic data for testing and development",
      "SQL queries for filtered post retrieval",
    ],
    tech: [
      "React",
      "React Router",
      "Express",
      "Node.js",
      "SQL",
      "PostgreSQL",
      "Authentication",
      "Database Polling",
    ],
    thumbnail: "/projects/forum/Forum-Main.png",
    images: [
      "/projects/forum/Forum-Main.png",
      "/projects/forum/Forum-Create.png",
      "/projects/forum/Forum-User-Profile.png",
      "/projects/forum/Forum-User-Login.png",
    ],
    category: "web",
    website: "https://forum-3nwm.onrender.com/",
    server: "https://forum-server-6tz1.onrender.com/",
    github: "https://github.com/Dylan-JM/week07-assignment",
  },
  {
    title: "Event Planner",
    slug: "event-planner",
    description:
      "Full-stack group project for discovering and creating local events to reduce social isolation.",
    tags: [
      "HTML",
      "CSS",
      "JavaScript",
      "Express",
      "PostgreSQL",
      "Supabase",
      "Full Stack",
      "Group Project",
    ],
    note: "⚠️ This project uses Supabase on the free tier. The database may be paused or removed at any time.",
    longDescription:
      "Event Planner is a full-stack web application built week-long bootcamp assignment in week 5. The app helps users find and create local events — from conventions and sports to social groups and entertainment — with the goal of reducing social isolation and encouraging community connection. I worked as part of a small team to design, build, and deploy the app using HTML, CSS, vanilla JavaScript, Express, and PostgreSQL. We implemented dynamic DOM manipulation, async Fetch calls, and database operations via Supabase. Stretch goals included category filtering, responsive design, and a polished UI. We also documented our planning process with wireframes, Trello boards, and daily stand-ups.",
    features: [
      "Browse and create local events across multiple categories",
      "Responsive design with intuitive navigation",
      "Dynamic DOM manipulation using vanilla JavaScript",
      "Express server with multiple endpoints",
      "PostgreSQL database integration via Supabase",
      "Category filtering and event creation form",
      "Group collaboration using Git, Trello, and daily stand-ups",
      "Presentation and README with architecture overview",
    ],
    tech: [
      "HTML",
      "CSS",
      "JavaScript",
      "Express",
      "PostgreSQL",
      "Supabase",
      "Git",
      "Trello",
    ],
    website: "https://event-planner-12va.onrender.com/",
    server: "https://event-planner-server-9pnz.onrender.com/",
    github: "https://github.com/Dylan-JM/week05-assignment",
    thumbnail: "/projects/event-planner/Event-Planner-Main.png",
    images: [
      "/projects/event-planner/Event-Planner-Main.png",
      "/projects/event-planner/Event-Planner-Find-Events.png",
      "/projects/event-planner/Event-Planner-Create-Events.png",
    ],
    category: "web",
  },
];
